AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodeBuildServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "example-pipeline-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: pipeline-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"
              - Sid: CloudWatchLogsPolicy
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DeleteLogGroup'
                Resource: '*'
              - Sid: S3GetObjectPolicy
                Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                Resource: '*'
              - Sid: S3PutObjectPolicy
                Effect: Allow
                Action:
                  - 's3:PutObject'
                Resource: '*'
              - Sid: S3BucketIdentity
                Effect: Allow
                Action:
                  - 's3:GetBucketAcl'
                  - 's3:GetBucketLocation'
                Resource: '*'

  GitHubConnection:
    Type: 'AWS::CodeStarConnections::Connection'
    Properties:
      ConnectionName: example-connection
      ProviderType: GitHub  
  DeployBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Suspended
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      Name: !Ref 'AWS::StackName'
      ArtifactStore:
        Type: S3
        Location: !Ref DeployBucket
      RoleArn: !GetAtt
        - CodeBuildServiceRole
        - Arn     
      Stages:
        - Name: Source
          Actions:
            - Name: Get-sources
              ActionTypeId:
                Version: '1'
                Owner: AWS
                Category: Source
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: react-code-artifact
              Configuration:
                ConnectionArn: !Ref GitHubConnection
                FullRepositoryId: !Sub "mauro-fanton/example-aws-cicd"
                BranchName: 'master'
              RunOrder: 1
        - Name: UnitTests
          Actions:
            - Name: UnitTests
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              RunOrder: 1
              Configuration:
                ProjectName: 'UnitTests'
              InputArtifacts:
                - Name: react-code-artifact

  UnitTests:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "UnitTests"
      ServiceRole: !GetAtt
        - CodeBuildServiceRole
        - Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: "buildspec.yml"
      TimeoutInMinutes: 10 
